let easyWords = [
    "CHAIR", "FLEUR", "POMME", "PAPIER", "TABLE", "CHAUD", "VACHE", "VRAIE", "MANGER", "LIVRE",
    "SOLEI", "BESOIN", "AMOUR", "RENDE", "POULE", "SOURI", "CROIX", "VOIR", "PLAGE", "MAISU",
    "RIRE", "CLAIR", "FAIRE", "LOUIS", "COEUR", "DOUCE", "GRACE", "PRETE", "COEUR", "BATON",
    "HAUTE", "PIQUE", "VITES", "JOLIE", "FILLE", "FLAMME", "RAPIDE", "CHEVE", "COUPE", "REGLE",
    "PILOT", "NAGER", "PILOT", "VOTRE", "SURGE", "PONCE", "MERVE", "PUISS", "LOVER", "TONAL",
    "FRUIT", "CIGUE", "CUVE", "HUMUS", "JONCE", "MELLE", "AVERT", "CAGEE", "RIDER", "NUIT",
    "CYCLE", "BALAI", "VOILE", "TOILE", "PILE", "CASS", "HIVER", "CARES", "ENFUI", "VAIN", "RUEZ",
    "FIRME", "ROUGE", "LUMEN", "NAGER", "MARTE", "RUBAN", "VACHE", "SAVOIR", "REPOS", "FROID",
    "FLEUR", "MARCH", "DOUTE", "AVION", "MELLE", "LOVER", "GOUTE", "SAISE", "NASTO", "LOUIS",
    "MOTIF", "DEUXE", "JOUER", "SOUF", "LITRE", "BLOCS", "SOUCE", "SAVOIR", "PUISS",
    "SIXTE", "MARES", "PANIE", "POMME", "CLORE", "PALES", "TEXTE", "RAGUE", "VITRE"
  ];

let middleWords = [
  "ECOLE", "VOITURE", "POMMIER", "LIVREUR", "CHAINE", "MAGNET", "REACTIF", "PLATINE", "CAVALIER", "MENTAL",
  "CASSERO", "SOUVENIR", "PLIABLE", "EXAMEN", "REGNE", "BANDEAU", "PORTIER", "VITESSE", "JOYEUX", "CONSOLE",
  "MARCHE", "BEAUTE", "FUTILE", "TISSAGE", "COULER", "REPOSER", "ATELIER", "ARMORIC", "GLOIRE", "TONNEAU",
  "CREDO", "FERRAIL", "RESPIR", "MARCHER", "CONGEL", "CHOSES", "RAYON", "GROUPE", "MIGRER", "TRAVAIL",
  "RELOU", "TISSER", "CHAULE", "RAVAGE", "SAVANE", "HUMIDE", "CHARME", "MIRAGE", "FOURNI", "IMPOSS",
  "NOUVELLE", "MARCHE", "RETIRE", "AGENCE", "TOURNER", "SOMME", "TISSEUR", "EXAMINE", "RANGEE", "REVENIR",
  "POURTOI", "PROPOS", "VISITE", "CITEUR", "IMPRIME", "BAGUET", "RECHER", "JACKAL", "FASHION", "VINTAGE",
  "NETTOIE", "CAMERA", "OPERA", "VENTAL", "EXPERI", "SERIES", "VOYAGE", "ALLOME", "RENDEZ", "CARREL",
  "HONNEUR", "SECTEUR", "SEULE", "AIGUIL", "PENDRE", "TASSER", "CONSEIL", "ECHANT", "FINISH", "ESPACE",
  "COUTE", "BEGNEU", "FABRIE", "ANIMEE", "RESOIR", "FORMAT", "SIFTER", "FIEUX", "JAPONS", "INTOUR",
  "DAMES", "BLOUSE", "LOVEL", "CLOSET", "GENIE", "MODELE", "ROTI", "EQUIPE", "SAVOIR", "PORTE",
  "ALIGNE", "CHOCOL", "BIBLE", "FAIRM", "RESORT"
];

let hardWords = [
    "DEVELOPPEUR", "PROGRAMMATION", "INFORMATIQUE", "COMPUTER", "EXCEPTIONNEL", "CONSTRUCTION", "ORDINATEUR", "ADMINISTRATION", "IMPOSSIBLE", "MANIFESTER",
    "DEFINITION", "RECONNAISSANCE", "ENTREPRISE", "DOCUMENTS", "CONCERNE", "METHODE", "SOLUTION", "SUPPORTER", "ENSEIGNANT", "COLLECTEUR",
    "ECONOMIQUE", "ARCHITECTE", "APPRECIATION", "PERSONNEL", "INVENTAIRE", "SERVEUR", "COMPARER", "EXISTENCE", "COTISATION", "REPRESENTER",
    "CONFORMER", "VALORISER", "REACTIF", "EXPERIENCE", "COUTUMIER", "CONSEQUENT", "DELAIS", "BUDGET", "RELATION", "MONNAIE",
    "RECUPERER", "CONFORMITE", "EQUIPIER", "ENCHAINER", "REGLAGE", "FAVORISER", "ANNONCE", "PORTFOLIO", "CONTACTS", "MOTEUR",
    "COORDONNE", "INHUMAIN", "CONVAINCRE", "CHRONO", "REMUNERE", "PRESENTER", "REVOLUTION", "CIRCULATION", "REPARATION", "AFFICHER",
    "OBTENIR", "TRANQUILLE", "RAPIDEMENT", "ATTENDRE", "INQUIETUDE", "ANNONCER", "INNOVATION", "TRAVAILLE", "ENDEUILLER", "DIVERSITE",
    "CRITIQUE", "OBSEQUANT", "DISPARAIT", "ACTIVITE", "MODERATEUR", "EVALUER", "PRESENTATION", "MENSUELLE", "PROGRES", "DEFI",
    "SUCCES", "REPOS", "ESTIMATION", "CONTROLE", "DECISION", "COLLABORATEUR", "RETARD", "CORRIGER", "PREDICTION", "EXPERIMENTER",
    "METAMORPHOSE", "PREDIRE", "SOMMAIRE", "DOCUMENT", "APPLICATEUR", "CONDITION", "DISPOSITIF", "MONITORING", "CATEGORIE", "CARACTERE",
    "ACTUALITE", "REACTUALISER", "EXEMPLAIRE", "DISTRIBUER", "AMELIORER", "FONCTIONNER", "MONTEE", "EXERCICE", "RESULTAT", "DISPONIBLE",
    "OPPORTUN", "TRADUCTION", "IMPOSSIBILITE", "SYSTEME", "ESSENTIAL", "TECHNOLOGIE", "VIRTUALISER", "MANIPULER", "ASSURER", "MEILLEUR",
    "POSITIVE", "FACILITER", "SIGNALER", "DEPLACER", "MAJORER", "REDDITION", "CALCULER", "INTERFACE", "SECURISER", "CONSTITUER"
  ];